name = "TestRegistry"
uuid = "ee4937aa-5703-11e9-0078-5126174c7110"
repo = "https://github.com/kdw503/TestRegistry.git"

description = """
kdw503 julia package registry where people can
register any package within lab scope.
"""

[packages]
cd2a8086-c8df-11e8-3fc2-5755b5e60617 = { name = "TestPkg", path = "T/TestPkg" }
