
name: TriggerTagBot
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get updated package name
        id: pkg
        run: |
          PACKAGENAME=$(git diff HEAD^ --stat | grep /Versions.toml | cut -d/ -f2 | uniq)
          echo "::set-output name=packagename::$PACKAGENAME"
      - name: Run `repository_dispatch` on updated repo, to trigger tagbot
        run: |
          echo "${steps.pkg.outputs.packagename}"
          curl -X POST https://api.github.com/repos/kdw503/TestPkg.jl/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H "Authorization: token ${TAGBOT_PAT}" \
          --data '{"event_type": "TriggerTagBot_TestPkg", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
