name: TriggerTagBot
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get updated package name
        id: pkg
        run: |
          PACKAGENAME=$(git diff HEAD^ --stat | grep /Versions.toml | cut -d/ -f2 | uniq)
          echo "::set-output name=packagename::$PACKAGENAME"
          echo "Package name is: $PACKAGENAME"
          echo "packagename=$PACKAGENAME" >> "$GITHUB_ENV"
      - name: Run `repository_dispatch` on updated repo, to trigger tagbot
        env:
          TAGBOT_PAT: ${{ secrets.TAGBOT_PAT }}
        run: |
          if [ -z "$packagename" ]; then
            echo "Error: Package name is empty"
            exit 1
          fi
          echo "${{steps.pkg.outputs.packagename}}"
          curl -X POST https://api.github.com/repos/HolyLab/${packagename}.jl/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H "Authorization: token $TAGBOT_PAT" \
          -H "Content-Type: application/json" \
          --data "{\"event_type\": \"TriggerTagBot_${packagename}\", \"client_payload\": { \"repository\": \"$GITHUB_REPOSITORY\" }}"
          # --data '{"event_type": "TriggerTagBot_TestPkg", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
          # -H "Authorization: token ${TAGBOT_PAT}" \ Authorization fail
          # -H "Authorization: token actual_token" \ Authorization succeeded and one time repositery_dispatch is triggered

