name: TriggerTagBot
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get updated package name
        id: pkg
        run: |
          PACKAGENAME=$(git diff HEAD^ --stat | grep /Versions.toml | cut -d/ -f2 | uniq)
          echo "::set-output name=packagename::$PACKAGENAME"
          echo "${{ steps.pkg.outputs.packagename }}"
          echo "${{PACKAGENAME}}"
      - name: Run `repository_dispatch` on updated repo, to trigger tagbot
        run: |
          curl -X POST https://api.github.com/repos/HolyLab/${{ steps.pkg.outputs.packagename }}.jl/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.TAGBOT_PAT }} \
          --data '{"event_type": "TriggerTagBot_${{ steps.pkg.outputs.packagename }}", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
          # --data '{"event_type": "TriggerTagBot_TestPkg", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
          # -H "Authorization: token ${TAGBOT_PAT}" \ Authorization fail
          # -H "Authorization: token actual_token" \ Authorization succeeded and one time repositery_dispatch is triggered

